branches:
  only:
  - master

language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      env: TOXENV=py27
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py35

sudo: required

install:
  - source install_conda.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update;
       brew install gcc;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       sudo apt-get install liblapack3;
    fi
  - pip install pip --upgrade
  - pip install -q -r requirements.txt --upgrade

script: invoke build_all --nopy27

notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: always
    on_failure: always
