branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      platform: x64
      STANDALONE: "FALSE"
      CONDA_PY: "35"
      CONDA_BUILD: "TRUE"
      SPLIT_RUN: "FALSE"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "conda install conda-build anaconda-client"
  - "conda update --all --yes"

build: false

test_script:
  - "python login.py"
  - "build_win64.bat"

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true