{% set name = "bader" %}
{% set version = "0.9.5" %}
{% set md5 = "2bc54f94d4c6d2aac9fd59b7f8948fd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://theory.cm.utexas.edu/henkelman/code/bader/download/bader.tar.gz

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gcc # [linux]

test:
  commands:
    - bader -h

about:
  home: http://theory.cm.utexas.edu/henkelman/code/bader
  license: MIT
  summary: Bader charge analysis library of the Henkelman group
  description: |
    A fast algorithm for doing Bader's analysis on a charge density grid. The 
    program can read in charge densities in the VASP CHGCAR format, 
    or the Gaussian CUBE format. The program outputs the total charge associated 
    with each atom, and the zero flux surfaces defining the Bader volumes.