{% set name = "MatMethods" %}
{% set version = "0.3" %}
{% set md5 = "abd132446ad7b7653e1c10770dd9430e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mmwf = matmethods.scripts.mmwf:mmwf

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - fireworks
    - pymatgen
    - pymatgen-db
    - custodian
    - monty
    - paramiko
    - coverage
    - tqdm
    - six
    - pybtex

test:
  # Python imports
  imports:
    - matmethods
    - matmethods.vasp.workflows

  commands:
    - mmwf --help

about:
  home: https://github.com/hackingmaterials/MatMethods
  license: modified BSD
  summary: 'MatMethods materials science workflow software'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
