{% set name = "MatMethods" %}
{% set version = "0.3" %}
{% set md5 = "abd132446ad7b7653e1c10770dd9430e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch_python: True
  number: 0
  script: python setup.py install 
  entry_points:
    - mmwf = matmethods.scripts.mmwf:mmwf

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - FireWorks>=1.3.8
    - pymatgen>=4.5.2
    - pymatgen-db>=0.6.4
    - custodian>=1.0.3
    - monty>=0.9.6
    - paramiko>=1.15.0
    - unittest2>=1.1.0
    - coverage>=4.2
    - tqdm>=4.8.4
    - six>=1.10.0
    - pybtex>=0.20.1

test:
  # Python imports
  imports:
    - matmethods
    - matmethods.vasp.workflows

  commands:
    - mmwf --help

about:
  home: https://github.com/hackingmaterials/MatMethods
  license: modified BSD
  summary: 'MatMethods materials science workflow software'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
