{% set name = "enumlib" %}
{% set version = "1.0.4" %}
{% set md5 = "2bc54f94d4c6d2aac9fd59b7f8948fd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

requirements:
  build:
    - git
    - gcc # [linux]
    - m2w64-gcc-fortran # [win]
    - make # [win]

#test:
#  commands:
#    - enum.x

about:
  home: https://github.com/msg-byu/enumlib
  license: MIT
  summary: Enumeration library for generating derivative structures.
  description: |
    This code generates the derivative superstructures of a parent lattice. 
    It works for general lattices, including "multilattices," like HCP, which 
    have more than one lattice point in the unit cell. The code can enumerate 
    over all concentrations or in a restricted concentration range.
