{% set name = "BoltzTraP" %}
{% set version = "1.2.5" %}
{% set md5 = "6623d4393bce2e178b073f75f283eee6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://www.icams.de/content/uploads/{{ name|lower }}/{{ name }}.tar.bz2
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - gcc
    - m2w64-gcc-fortran # [win]
    - make # [win]

#test:
#  commands:
#    - x_trans -h

about:
  home: http://www.icams.de/research/software-development/boltztrap
  license: MIT
  summary: Enumlib of Gus Hart
