{% set name = "BoltzTraP" %}
{% set version = "1.2.5" %}
{% set md5 = "6623d4393bce2e178b073f75f283eee6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://www.icams.de/content/uploads/{{ name|lower }}/{{ name }}.tar.bz2
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - gcc
    - m2w64-gcc-fortran # [win]
    - make # [win]

#test:
#  commands:
#    - x_trans -h

about:
  home: http://www.icams.de/research/software-development/boltztrap
  license: MIT
  summary: 'Boltzmann Transport Properties (BoltzTraP) is a program for calculating the semi-classic transport coefficients'
  description: |
    Boltzmann Transport Properties (BoltzTraP) is a program for calculating the semi-classic 
    transport coefficients. The code uses a mesh of self-consistent band energies and is 
    interfaced to the WIEN2k, AB-INIT, SIESTA, VASP and QuantumEspresso programs. A paper 
    about the code has been published, which must be cited if the program is used: 
    Madsen, G. K. H.*; Singh, D. J. Comput. Phys. Commun. 2006 175, 67
