{% set name = "smoqe" %}
{% set version = "0.1.3" %}
{% set md5 = "a5914e7b0b5804035c5bdf0f3a20d58b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - docutils >=0.3

  run:
    - python
    - docutils >=0.3
    - pymongo

test:
  imports:
    - smoqe

about:
  home: https://github.com/dangunter/smoqe/
  license: LGPL
  summary: 'Simple MongoDB Query Engine (SMoQE)'
  license_family: LGPL

